### ISSUE TITLE
Error when using another Ligand

### ISSUE THREAD

**Issue by nohandsomewujun** [OptiMaL-PSE-Lab/DeepDock#12]
I tried to use different ligands to dock with the proteins in the repo .According to the files in your examples, when I tried to dock with 2br1_protein.pdb and 2wtv_protein.pdb, it worked .But when I tried to dock with 1z6e_protein.pdb, it failed.
And error msg:
```txt
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    compute_inp_surface(target_filename, ligand_filename, dist_threshold=10)
  File "/DeepDock/deepdock/prepare_target/computeTargetMesh.py", line 70, in compute_inp_surface
    structure = structures[0] # 'structures' may contain several proteins in this case only one.
  File "/opt/conda/lib/python3.6/site-packages/Bio/PDB/Entity.py", line 45, in __getitem__
    return self.child_dict[id]
KeyError: 0
``` 
It seems like something wrong when generating 1z6e_protein_15A.pdb.
And my Ligand file:
[new1.mol2.zip](https://github.com/OptiMaL-PSE-Lab/DeepDock/files/8775945/new1.mol2.zip)
Thank you!

**Comment by Chemwzd** [comment]
I got the seem message when I tried to dock new ligand, have you solve this error yet?

**Comment by nohandsomewujun** [comment]
> I got the seem message when I tried to dock new ligand, have you solve this error yet?

Well, I didn't solve the problem and go looking for a new tool.
