### ISSUE TITLE
Dataload error while running training_DeepDock.ipynb

### ISSUE THREAD

**Issue by Nanco-L** [OptiMaL-PSE-Lab/DeepDock#5]
Hello, I try to run `training_DeepDock.ipynb`.
With my environment `pytorch=1.10.2` and `pyg=2.0.3`, I face following error while loading preprocessed data with following error

```
Traceback (most recent call last):                                                                                              
  File "/db2/users/kyuhyunlee/DeepDock_test/train_deepdock.py", line 21, in <module>                                            
    db_complex = PDBbind_complex_dataset(data_path=deepdock.__path__[0]+'/../data/dataset_deepdock_pdbbind_v2019_16K.tar',      
  File "/db2/users/kyuhyunlee/git_repos/DeepDock/deepdock/utils/data.py", line 60, in __init__                                  
    self.data = [i for i in self.data if not np.isnan(i[1].x.numpy().min())]                                                    
  File "/db2/users/kyuhyunlee/git_repos/DeepDock/deepdock/utils/data.py", line 60, in <listcomp>                                
    self.data = [i for i in self.data if not np.isnan(i[1].x.numpy().min())]                                                    
  File "/db2/users/kyuhyunlee/anaconda3/envs/py39_default/lib/python3.9/site-packages/torch_geometric/data/data.py", line 642, i
n x                                                                                                                             
    return self['x'] if 'x' in self._store else None                                                                            
  File "/db2/users/kyuhyunlee/anaconda3/envs/py39_default/lib/python3.9/site-packages/torch_geometric/data/data.py", line 357, i
n __getattr__                                                                                                                   
    raise RuntimeError(                                                                                                         
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing
 dataset, remove the 'processed/' directory in the dataset's root folder and try again.
```

Is there any method to fix it? I already know `DeepDock` need older version of `pytorch` and `pytorch_geometric` as prerequisities but It will be nice to use `DeepDock` with latest version of `pytorch` and `pyg`.

**Comment by Zhanghaotian1** [comment]
Dear Nanco-L, I think this error is caused by the version conflict, as DeepDock mentioned in experiment.txt, the PyG and torch are in a lower version. I also met this problem, and I'm trying to process data with a higher version PyG, but I don't see where is the default_config module for DeepDock...
